import type { Metadata } from "next";
import { Inter } from "next/font/google";
import App from "@/components/App";
import ColorModeProvider from "@/components/ColorModeProvider";
import { CssBaseline } from "@mui/material";
import { ApolloProvider } from "@/components/ApolloProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tech4Med Tool",
  description: "Generated by create next app",
};

export default function RootLayout(props: any) {
  return (
    <ColorModeProvider>
      <CssBaseline />
      <ApolloProvider>
        <html lang="en">
          <body className={inter.className}>
            <App>{props?.children}</App>
          </body>
        </html>
      </ApolloProvider>
    </ColorModeProvider>
  );
}
